---
name: "Ani-Sync"
guid: "c78f11cf-93e6-4423-8c42-d2c255b70e47"
version: "3.3"
targetAbi: "10.9.6.0"
framework: "net8.0"
owner: "vosmiic"
overview: "Synchronize anime watch status"
description: >
  Synchronize anime watch status between Jellyfin and anime tracking sites.
category: "General"
artifacts:
  - "jellyfin-ani-sync.dll"
changelog: |1-
  - Added 429 Too Many Requests handling with backoff.
  - Increased plugin API security
  - Config page overhaul
  - Improved anime detection